# Dependencies

# Permalinks
permalink:        pretty


# Setup
title:            Flowing Forward
tagline:          ''
description:      'A reproducible workflow for studying groundwater changes in the Colorado River Basin and beyond' 
url:              "https://uwescience.github.io"
baseurl:          "/DSSG2023-Groundwater"


paginate:         5

# Custom vars
version:          0.0.0

github:
  repo:           https://github.com/uwescience/DSSG2023-Groundwater
