# Dependencies

# Permalinks
permalink:        pretty


# Setup
title:            DSSG 2023 Groundwater
tagline:          ''
description:      'A 2023 Data Science for Social Good summer fellowship project at the University of Washington' 
url:              "https://uwescience.github.io"
baseurl:          "/DSSG2023-Groundwater"


paginate:         5

# Custom vars
version:          0.0.0

github:
  repo:          https://github.com/uwescience/DSSG2023-Groundwater
